### ISSUE TITLE
Game White Screens after install, along with other issues

### ISSUE THREAD

**Issue by Hexdrix** [rebane2001/StickRPG2-HD#1]
Firstly, when installing, and after the download has verified, _"The system cannot find C:\Program Files (x86)\Steam\steamapps\common\Stick RPG 2 Director's Cut.exe"_ This happens at several points.

This did not initially pose an issue, as I am able to manually start the game during the _"waiting 10 seconds..."_ message. This then led to a _"SUCCESS: The process 'Stick RPG 2 Director's Cut.exe' with PID 21096 has been terminated."_

However, after rearranging files...

_The system cannot find the file specified.
A duplicate file name exists, or the file
cannot be found.
A duplicate file name exists, or the file
cannot be found.
A duplicate file name exists, or the file
cannot be found.
Preparing to patch files...
Patching flashplayer_32_sa...
Patching HD textures for dat.swf...
The system cannot find the file specified.
xdelta3: file open failed: read: dat_original.swf: The system cannot find the file specified.
Patching HD textures for Minigames.swf...
The system cannot find the file specified.
xdelta3: file open failed: read: Minigames_original.swf: The system cannot find the file specified.
Creating final HD exe...
flashplayer_patched.exe
C:\Users\HEXDR\Downloads\StickRPG2-HD-v1.0.0\patch\finalize.hex
        1 file(s) copied.
Done! Press any key to exit.
Press any key to continue . . ._

This then leads to nothing, then when Stick RPG 2 is launched, blank white screen that does not load. Steam overlay appears to be loading as my FPS is showing, but no game. 

I have a theory that it is tied somehow to where the patcher is trying to pull from. I have my steam games on separate libraries, with the main installation on its own drive. This leads to me having a different set of folders, most notably that there is no Steam folder, only the SteamLibrary folder in its place **(M:\SteamLibrary\steamapps\common\Stick RPG 2)** Not only that, but my Stick RPG is on my (M:) drive. Even switching to my (C:) drive causes the same issue, as I have an extra folder between Steam and steamapps, that being the SteamLibrary folder (C:\Program Files (x86)\Steam\SteamLibrary\steamapps)

Tried rearranging folders and will try a manual patch later.

**Comment by Hexdrix** [comment]
I did not notice this prior, but before downloading

_Looking for Stick RPG 2 instances...
Found Stick RPG 2 in M:\SteamLibrary\steamapps\common\Stick RPG 2\Stick RPG 2 Director's Cut.exe
SUCCESS: The process "Stick RPG 2 Director's Cut.exe" with PID 29688 has been terminated.
Creating a backup of the original game as original.exe
        1 file(s) copied.
Could Not Find M:\SteamLibrary\steamapps\common\Stick RPG 2\*.swf
        1 file(s) copied.
Downloading required files..._

**Comment by rebane2001** [comment]
Hey, how did you implement your manual patch? It seems like you may be missing a backslash from the end of the path that gets used.

If you put the game on the C: drive and ask Steam to verify files before using the patch, does it work?

What Windows version/build are you using?

**Comment by rebane2001** [comment]
Never mind, I just realized I had forgotten a hardcoded path in the script.

Try downloading the latest release (v1.0.1) and let me know if that one works for you.

**Comment by Hexdrix** [comment]
The patch now works! All the files found the right spot. It wiped my saves, but eh, i wasn't far anyhow. Thanks for the work.

As a side note, manual patching did also work, but not as well; lots more ui bugs.

**Comment by rebane2001** [comment]
Fyi your saves should still exist if you go back to the original game version in the original install path. Perhaps I should make an install transfer tool of some sort.

**Comment by rebane2001** [comment]
Fyi your saves should still exist if you go back to the original game version in the original install path. Perhaps I should make an install transfer tool of some sort.
